version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    reviewers:
      - 'MaSpeng'
    schedule:
      interval: 'weekly'
      time: '08:00'
      timezone: 'Europe/Berlin'

  - package-ecosystem: 'devcontainers'
    directory: '/'
    reviewers:
      - 'MaSpeng'
    schedule:
      interval: 'weekly'
      time: '08:00'
      timezone: 'Europe/Berlin'

  - package-ecosystem: 'composer'
    directory: '/'
    reviewers:
      - 'MaSpeng'
    schedule:
      interval: 'weekly'
      time: '08:00'
      timezone: 'Europe/Berlin'
