version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '08:00'
      timezone: 'Europe/Berlin'

  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '08:00'
      timezone: 'Europe/Berlin'

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '08:00'
      timezone: 'Europe/Berlin'
