version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    reviewers:
      - 'MaSpeng'
    schedule:
      interval: 'weekly'
      time: '08:00'
      timezone: 'Europe/Berlin'

  - package-ecosystem: 'devcontainers'
    directory: '/'
    reviewers:
      - 'MaSpeng'
    schedule:
      interval: 'weekly'
      time: '08:00'
      timezone: 'Europe/Berlin'

  - package-ecosystem: 'docker'
    directory: '/'
    reviewers:
      - 'MaSpeng'
    schedule:
      interval: 'weekly'
      time: '08:00'
      timezone: 'Europe/Berlin'

  - package-ecosystem: 'composer'
    directories:
      - '/'
      - '/tools/php-cs-fixer'
      - '/tools/phpstan'
      - '/tools/phpunit'
    reviewers:
      - 'MaSpeng'
    schedule:
      interval: 'weekly'
      time: '08:00'
      timezone: 'Europe/Berlin'
