failure-threshold: error

ignored:
  # pin apk versions
  - DL3018
  # pin npm versions
  - DL3016
  # shell option pipefail
  - DL4006

trustedRegistries:
  - docker.io
  - ghcr.io
  - mcr.microsoft.com