version: 2.1

jobs:
  prepare:
    docker:
      - image: composer:2
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Validating composer file
          command: composer validate --no-check-all --no-check-publish

      - run:
          name: Installing dependencies
          command: composer install --no-interaction

      - run:
          name: Installing tools
          command: composer bin all install --no-interaction

      - persist_to_workspace:
          root: ~/project
          paths:
            - vendor
            - tools/php-cs-fixer/vendor/
            - tools/phpstan/vendor/
            - tools/phpunit/vendor/

  analysis:
    docker:
      - image: cimg/php:8.1.26
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD

    working_directory: ~/project

    steps:
      - checkout

      - attach_workspace:
          at: ~/project

      - run:
          name: Anlaysing code
          command: tools/phpstan/vendor/bin/phpstan analyze --ansi

  style-check:
    docker:
      - image: cimg/php:8.1.26
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD

    working_directory: ~/project

    steps:
      - checkout

      - attach_workspace:
          at: ~/project

      - run:
          name: Checking code style
          command: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --diff --verbose --ansi

  phpunit:
    docker:
      - image: cimg/php:8.1.26
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD

    working_directory: ~/project

    steps:
      - checkout

      - attach_workspace:
          at: ~/project

      - run:
          name: Executing unit tests
          command: |
            sudo pecl install pcov
            sudo docker-php-ext-enable pcov
            php tools/phpunit/vendor/bin/phpunit \
              --coverage-text \
              --coverage-clover=build/logs/coverage.clover.xml \
              --log-junit=build/test-results/phpunit/results.xml

      - persist_to_workspace:
          root: ~/project
          paths:
            - build

      - store_test_results:
          path: build/test-results

codacy-coverage-report:
  docker:
    - image: cimg/openjdk:8-jdk
      auth:
        username: $DOCKER_HUB_USERNAME
        password: $DOCKER_HUB_PASSWORD

  working_directory: ~/project

  steps:
    - checkout

    - attach_workspace:
        at: ~/project

    - coverage-reporter/send_report:
        coverage-reports: build/logs/coverage.clover.xml
        project-token: $CODACY_PROJECT_TOKEN

orbs:
  coverage-reporter: codacy/coverage-reporter@13.13.15

workflows:
  analyse-test:
    jobs:
      - prepare

      - analysis:
          requires:
            - prepare

      - style-check:
          requires:
            - prepare

      - phpunit:
          requires:
            - prepare
