name: code-check

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

env:
  COMPOSER_VERSION: 2.6.6

jobs:
  lint-analyse-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP with PECL extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          ini-values: zend.assertions = 1
          tools: composer:${{ env.COMPOSER_VERSION }}
          coverage: pcov

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> ${GITHUB_OUTPUT}

      - name: Restore Composer cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-Composer-V1-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-Composer-V1-

      - name: Restore vendor cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-Vendor-V1-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-Vendor-V1-

      - name: Restore tools vendor cache
        uses: actions/cache@v3
        with:
          path: tools/**/vendor
          key: ${{ runner.os }}-Tools-Vendor-V1-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-Vendor-V1-

      - name: Restore PHPStan cache
        uses: actions/cache@v3
        with:
          path: var/phpstan
          key: ${{ runner.os }}-PHPStan-V1-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-PHPStan-V1-

      - name: Restore PHP Coding Standards Fixer cache
        uses: actions/cache@v3
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.os }}-PHPCSFIXER-V1-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-PHPCSFIXER-V1-

      - name: Restore PHPUnit result cache
        uses: actions/cache@v3
        with:
          path: .phpunit.cache
          key: ${{ runner.os }}-PHPUnit-V1-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-PHPUnit-V1-

      - name: Install dependencies
        run: composer install

      - name: Lint source code
        run: composer run-script -- lint-code

      - name: Analyse code
        run: composer run-script -- analyse-code

      - name: Run tests and report code coverage
        run: composer run-script -- test --coverage-clover clover.xml --coverage-text

      - name: Check test coverage
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: 100
          filename: clover.xml
