name: docker-check

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  hadolint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true