name: markdown-check

on:
  merge_group:
    types:
      - checks_requested

  push:
    branches:
      - 'main'

  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Markdown files
        uses: nosborn/github-action-markdown-cli@v3
        with:
          files: '. .github/*.md'
