name: markdown-check

on:
  merge_group:
    types:
      - checks_requested

  push:
    branches:
      - 'main'

  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v24
        with:
          globs: |
            .github/*.md
            *.md
            docs/*.md
