name: shell-check

on:
  merge_group:
    types:
      - checks_requested

  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Shell script files
        uses: ludeeus/action-shellcheck@2.0.0
