name: yaml-check

on:
  merge_group:
    types:
      - checks_requested

  push:
    branches:
      - 'main'

  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  yamllint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check YAML files
        uses: ibiqlik/action-yamllint@v3
